version: '2.1'

services:
  ga:
    build: './server'
    container_name: ga
    environment:
      - PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=ga
      - MYSQL_PASSWORD=4t9wegcvbYSd
      - MYSQL_DATABASE=gitlab_analytics
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      ganet:
        aliases:
          - gaserver

  mysql:
    image: mariadb:5.5.60
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=gitlab_analytics
      - MYSQL_USER=ga
      - MYSQL_PASSWORD=4t9wegcvbYSd
    networks:
      - ganet
  grafana:
    image: grafana/grafana:5.1.4
    container_name: grafana
    user: root
    volumes:
      - ./grafana/:/etc/grafana/
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - ganet
networks:
  ganet:
    driver: bridge
    driver_opts:
      # TODO This config is only useful in the internal network of my company.
      com.docker.network.driver.mtu: 1450
