version: '2.1'

services:
  ga:
    build: './server'
    container_name: ga
    environment:
      - PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=ga
      - MYSQL_PASSWORD=4t9wegcvbYSd
      - MYSQL_DATABASE=gitlab_analytics
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      ganet:
        aliases:
          - gaserver

  mysql:
    image: mariadb:5.5.60
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=gitlab_analytics
      - MYSQL_USER=ga
      - MYSQL_PASSWORD=4t9wegcvbYSd
    networks:
      - ganet
  mongo:
    image: mongo:4.4-focal
    container_name: gamongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ga
      - MONGO_INITDB_ROOT_PASSWORD=4t9wegcvbYSd
    networks:
      - ganet
  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    user: root
    volumes:
      - ./grafana/:/etc/grafana/
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - ganet
networks:
  ganet:
    driver: bridge
