CREATE TABLE `gitlab_commits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `project_id` int(11) NOT NULL,
  `project_path` varchar(128) CHARACTER SET latin1 NOT NULL,
  `commit_id` char(40) CHARACTER SET latin1 NOT NULL,
  `title` varchar(72) NOT NULL,
  `created_at` datetime NOT NULL,
  `parent_ids` int(11) NOT NULL,
  `message` varchar(255) NOT NULL,
  `author_name` varchar(64) NOT NULL,
  `author_email` varchar(64) CHARACTER SET latin1 NOT NULL,
  `authored_date` datetime NOT NULL,
  `committer_name` varchar(64) NOT NULL,
  `committer_email` varchar(64) NOT NULL,
  `committed_date` datetime NOT NULL,
  `line_additions` int(11) DEFAULT NULL,
  `line_deletions` int(11) DEFAULT NULL,
  `line_total` int(11) DEFAULT NULL,
  `ignore` int(11) DEFAULT '0' COMMENT 'ignore this commit when analyze contribution',
  PRIMARY KEY (`id`),
  UNIQUE KEY `commit_id` (`commit_id`,`project_id`) USING BTREE,
  KEY `author_email` (`author_email`),
  KEY `author_name` (`author_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;